# Generated by Django 3.2.5 on 2022-04-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_dp04'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dp04',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dp05',
            name='id',
        ),
        migrations.AddField(
            model_name='dp04',
            name='GEOID',
            field=models.CharField(default='na', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dp05',
            name='GEOID',
            field=models.CharField(default='na', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
