# Generated by Django 3.2.5 on 2022-04-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_auto_20220419_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dp04',
            name='GEOID',
        ),
        migrations.RemoveField(
            model_name='dp05',
            name='GEOID',
        ),
        migrations.AlterField(
            model_name='dp04',
            name='GEO_ID',
            field=models.CharField(default='na', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dp05',
            name='GEO_ID',
            field=models.CharField(default='na', max_length=255, primary_key=True, serialize=False),
        ),
    ]
