# Generated by Django 3.2.5 on 2022-04-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_auto_20220419_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProfileVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variables', models.CharField(max_length=255)),
            ],
        ),
    ]
