# Generated by Django 3.2.5 on 2022-04-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0008_auto_20220424_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataprofilevars',
            name='id',
        ),
        migrations.AddField(
            model_name='dataprofilevars',
            name='Name',
            field=models.CharField(default='na', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='dataprofilevars',
            name='name',
            field=models.CharField(default='na', max_length=255),
        ),
    ]
