# Generated by Django 3.2.5 on 2022-04-25 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0010_auto_20220424_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprofilevars',
            name='attributes',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='concept',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='group',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='hasGeoCollectionSupport',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='label',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='limit',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='name',
            field=models.CharField(default='na', max_length=300, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='predicateOnly',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='predicateType',
            field=models.CharField(default='na', max_length=300),
        ),
        migrations.AlterField(
            model_name='dataprofilevars',
            name='required',
            field=models.CharField(default='na', max_length=300),
        ),
    ]
